"""Increment memberAge for all members

Revision ID: ad8582b382a7
Revises: 261b85ff63ca
Create Date: 2023-12-16 13:39:36.383155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8582b382a7'
down_revision: Union[str, None] = '261b85ff63ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
op.execute("UPDATE members SET memberAge = memberAge + 1")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
